site_name: winsonYe's Wiki
site_description: 厚积薄发
site_url: https://xxxx2077.github.io/
repo_url: https://github.com/xxxx2077/winsonYe_Wiki
#remote_name: linyuxuanlin/Wiki_MkDocs
edit_uri: edit/main/docs/ # 编辑按钮的url

theme:
  name: material
  font: #false # 国内网络访问 Google 源可能会有问题
    text: "Noto Sans SC - local"
    #code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # 检查用户系统配置是否为亮色
      scheme: default # 亮色模式
      primary: white # 基本颜色
      accent: purple # 按钮等互动块的颜色
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)" # 检查用户系统配置是否为暗色
      scheme: slate # 暗色模式
      primary: black # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  language: zh
  logo: img/logo-zip.png #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo-zip.png
  favicon: img/logo.svg #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo.svg #https://cos.ap-guangzhou.myqcloud.com/wiki-media-1253965369/doc/logo-zip.png
  features:
    - content.code.copy # 代码块复制按钮
    - content.action.edit # 文章编辑按钮
    - content.code.annotate # 代码注释按钮
    #- navigation.instant # Instant loading，像个单页应用
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.footer # 上一篇 / 下一篇导航按钮
    #- navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    - navigation.sections # 侧边栏分组显示
    #- navigation.expand # 导航栏自动展开
    - navigation.indexes # 组标题有专属页面
    - toc.follow # 目录自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索推荐
    #- navigation.prune # 导航修剪，仅渲染可见链接，优化文档数量超过100的站点（实验），会导致页面间跳转速度变慢
    #- search.highlight
  icon:
    repo: material/github
    #edit: material/pencil

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - javascripts/mathjax.js
        - javascripts/tex-mml-chtml.js
        - javascripts/embed.js
      css_files:
        - stylesheets/extra.css
  - rss:
      abstract_chars_count: -1 # -1 for full content
      #categories:
      # - tags
      #comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        #as_update: False
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: True
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 1000
      pretty_print: True
      match_path: "(zh|blog)/.*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: full
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft_if_future_date: true
  #TODO: make it runable
  # - git-revision-date-localized: # 页面下方创建和修改时间
  #     enable_creation_date: true
  #     type: timeago
  # - glightbox # 图片放大
  # - tags # 添加给单个文档添加tag标签
  # - statistics: # 统计页面字数、代码行数、阅读时间
  #     page_read_time: false
  #     page_check_metadata: comments
  #     page_template: "page_template/page_statistics.html"


extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
  generator: false
  analytics:
    # provider: google
    # # TODO: modify
    # property: G-QBB3SQMGLN # 如果克隆我的站点，请把这串代码改成你自己的
  mathjax: true
  # TODO: modify
  social:
    # - name: 友链 & 导航站
    #   link: https://nav.wiki-power.com/
    #   icon: fontawesome/regular/address-book
    # - name: 书摘
    #   link: http://digest.wiki-power.com/
    #   icon: fontawesome/regular/bookmark
    # - name: 资源仓库
    #   link: https://github.com/linyuxuanlin/File-host
    #   icon: fontawesome/regular/file-lines

copyright: Copyright &copy; 2025 winsonYe

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js
  - javascripts/mathjax.js #https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/latest.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js #https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/embed.js # https://viewer.altium.com/client/static/js/embed.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - 开发: 
    - Before Coding: 
      - computer_basic/index.md
      # - 操作系统
      # - 计算机网络
      # - 计算机组成原理
      # - 数据结构与算法
      - Shell: computer_basic/shell.md
      - Vim : computer_basic/vim.md
      - Git: computer_basic/Git.md
      - Linux: computer_basic/Linux.md 
    - 前端开发:
      - WebAssembly: software_development/frontend/WebAssembly.md
    - 后端开发: 
      - software_development/backend/index.md 
      - 语言: 
        - C++: software_development/backend/language/C++.md
        - Rust: software_development/backend/language/Rust.md
        - Java: software_development/backend/language/Java.md
        - Go: software_development/backend/language/Go.md
      - 存储:
        - software_development/backend/Storage&Database/index.md
        - MySQL: software_development/backend/Storage&Database/MySQL.md
        - Redis: software_development/backend/Storage&DatabaseRedis.md
      - 框架:
        - software_development/backend/Framework/index.md
        - RPC框架: software_development/backend/Framework/RPC.md
        - HTTP框架: software_development/backend/Framework/HTTP.md
      - 软件工程:
        - software_development/backend/Software_Engineering/index.md
        - 设计模式: software_development/backend/Software_Engineering/design_patterns.md
        - 软件架构与系统设计: 
          - software_development/backend/Software_Engineering/system_design/index.md
          - 微服务架构: 
            - software_development/backend/Software_Engineering/system_design/microService/index.md
            - 服务注册与服务发现: software_development/backend/Software_Engineering/system_design/microService/registry.md
            - DevOps:
              - Docker: software_development/backend/Software_Engineering/system_design/microService/DevOps/Docker.md
      - 中间件:
        - Kafka: software_development/backend/Middleware/Kafka.md
        - 消息队列: software_development/backend/Middleware/MessageQueue.md
      # - 分布式系统
        # - k8s
        # - tomcat
      - 面经: 
        - software_development/backend/interview/interview_experiences.md      
      - 项目:
        - 工程问题: software_development/backend/Project/project_knowledge.md      
        - 逸仙东华资源共享平台: software_development/backend/Project/yxdh.md
        - 抖音电商: 
          - software_development/backend/Project/tiktok_eCommerce/index.md
          - tutorail:
            - day1_微服务通信: software_development/backend/Project/tiktok_eCommerce/day1_rpc.md
    - 软件测试: 
      - 理论知识: software_development/software_test/software_test_theory.md
  - 数据结构&算法: 
    - 数据结构: 
      - algorithm/data_strucutre/index.md
      - 数组: algorithm/data_strucutre/array.md
      - 环状数组: algorithm/data_strucutre/circleArray.md 
      - 链表: algorithm/data_strucutre/linkedList.md  
      - 队列&栈: algorithm/data_strucutre/queue&stack.md 
      - 哈希表: algorithm/data_strucutre/hashTable.md 
      - 二叉树和多叉树: algorithm/data_strucutre/tree.md
      - 二叉堆: algorithm/data_strucutre/heap.md
      - 图: algorithm/data_strucutre/graph.md
    - 算法框架:
      - algorithm/algorithm_summary/index.md
      - 链表: algorithm/algorithm_summary/linkedList.md 
      - 数组: algorithm/algorithm_summary/array.md
      - 哈希表: algorithm/algorithm_summary/hashTable.md
    - leetcode刷题笔记:
      - algorithm/leetcode/index.md
      - 数组:
        - 二分查找:
          - 思路: algorithm/algorithm_summary/binary_search.md
          - 基本操作篇:
            - algorithm/leetcode/704 二分查找.md
            - algorithm/leetcode/34 在排序数组中查找元素的第一个和最后一个位置.md
            - algorithm/leetcode/35 搜索插入位置.md
          - 应用篇:
            - algorithm/leetcode/875 爱吃香蕉的珂珂.md
            - algorithm/leetcode/1011 在 D 天内送达包裹的能力.md
        - 双指针:
          - 原地移动元素:
            - algorithm/leetcode/26 删除有序数组中的重复项.md
            - algorithm/leetcode/27 移除元素.md
            - algorithm/leetcode/410 分割数组的最大值.md
          - 滑动窗口:
            - 思路: algorithm/algorithm_summary/window.md
            - algorithm/leetcode/3 无重复字符的最长子串.md
            - algorithm/leetcode/438 找到字符串中的所有字母异位词.md
            - algorithm/leetcode/239 滑动窗口的最大值.md
            - algorithm/leetcode/567 字符串的排列.md
            - algorithm/leetcode/76 最小覆盖子串.md
        - algorithm/leetcode/977 有序数组的平方.md
        - algorithm/leetcode/209 长度最小的子数组.md
        - algorithm/leetcode/54 螺旋矩阵.md
        - algorithm/leetcode/59 螺旋矩阵II.md
        - algorithm/leetcode/区间和.md
        - algorithm/leetcode/53 最大子数组和.md
        - algorithm/leetcode/56 合并区间.md
        - algorithm/leetcode/189 轮转数组.md
        - algorithm/leetcode/238 除自身以外数组的乘积.md
        - algorithm/leetcode/41 缺失的第一个正数.md
        - algorithm/leetcode/数组总结.md
      - 链表:
        - 链表的基本操作:
          - algorithm/leetcode/203 移除链表元素.md
          - algorithm/leetcode/707 设计链表.md
          - algorithm/leetcode/206 反转链表.md
          - algorithm/leetcode/24 两两交换链表中的节点.md
          - algorithm/leetcode/19 删除链表的第N个节点.md
          - algorithm/leetcode/876 链表的中间节点.md
          - algorithm/leetcode/160 相交链表.md
          - algorithm/leetcode/141 环形链表.md
          - algorithm/leetcode/142 环形链表II.md
          - algorithm/leetcode/21 合并两个升序链表.md
          - algorithm/leetcode/23 合并K个升序链表.md
        - algorithm/leetcode/25 K个一组翻转链表.md
        - 链表应用:
          - 链表的分解:
            - algorithm/leetcode/83 删除排序链表中的重复元素.md
            - algorithm/leetcode/82 删除排序链表中的重复元素II.md
          - 链表的合并:
            - algorithm/leetcode/264 丑数II.md
            - algorithm/leetcode/378 有序矩阵中第 K 小的元素.md
            - algorithm/leetcode/373 查找和最小的 K 对数字.md
          - 链表的运算:
            - algorithm/leetcode/2 两数相加.md
            - algorithm/leetcode/445 两数相加II.md
      - 双指针:
        - algorithm/leetcode/283 移动零.md
        - algorithm/leetcode/128 最长连续序列.md
        - algorithm/leetcode/11盛最多水的容器.md
        - algorithm/leetcode/15 三数之和.md
        - algorithm/leetcode/42 接雨水.md
      - 矩阵:
        - algorithm/leetcode/73 矩阵置零.md
        - algorithm/leetcode/48 旋转图像.md
        - algorithm/leetcode/240 搜索二维矩阵II.md
      - 子串:
        - algorithm/leetcode/560 和为k的子数组.md
      - 二叉树:
        - 二叉树遍历:
          - algorithm/leetcode/144 前序遍历.md
          - algorithm/leetcode/145 后序遍历.md
          - algorithm/leetcode/90 中序遍历.md
          - algorithm/leetcode/102 二叉树的层序遍历.md
        - 进阶二叉树:
          - algorithm/leetcode/226 翻转二叉树.md
          - algorithm/leetcode/101 对称二叉树.md
          - algorithm/leetcode/543 二叉树的直径.md
          - algorithm/leetcode/108 将有序数组转换为二叉搜索树.md
          - algorithm/leetcode/98 验证二叉搜索树.md
          - algorithm/leetcode/230 二叉搜索树第k小的元素.md
          - algorithm/leetcode/114 二叉树展开为链表.md
          - algorithm/leetcode/105 从前序与中序遍历构造二叉树.md
          - algorithm/leetcode/437 路径之和III.md
          - algorithm/leetcode/236 二叉树的最近公共祖先.md
          - algorithm/leetcode/124 二叉树中的最大路径和.md
        - 二叉树总结:
          - algorithm/leetcode/二叉树总结.md
      - 哈希表:
        - algorithm/leetcode/1 两数之和.md
        - algorithm/leetcode/49 字母异位词分组.md
        - algorithm/leetcode/242 有效的字母异位词.md
        - algorithm/leetcode/349 两个数组的交集.md
        - algorithm/leetcode/454 四数相加II.md
        - algorithm/leetcode/15 三数之和.md
      - 回溯问题:
        - algorithm/leetcode/77 组合.md
        - algorithm/leetcode/39 组合总和II.md
        - algorithm/leetcode/216 组合总和III.md
        - algorithm/leetcode/46 全排列.md
        - algorithm/leetcode/17 电话号码的字母组合.md
        - algorithm/leetcode/78 子集.md
      - 贪心:
        - algorithm/leetcode/121 买卖股票的最佳时机.md
        - algorithm/leetcode/55 跳跃游戏.md
        - algorithm/leetcode/45 跳跃游戏II.md
        - algorithm/leetcode/763 划分字母区间.md
      - 动态规划:
        - 基础题:
          - algorithm/leetcode/509 斐波那契数.md
          - algorithm/leetcode/70 爬楼梯.md
          - algorithm/leetcode/746 使用最小花费爬楼梯.md
          - algorithm/leetcode/62 不同路径.md
          - algorithm/leetcode/63 不同路径II.md
          - algorithm/leetcode/343 整数划分.md
          - algorithm/leetcode/96 不同的搜索树.md
        - 子序列系列:
          - algorithm/leetcode/300 最长递增子序列.md
          - algorithm/leetcode/674 最长连续子序列.md
          - algorithm/leetcode/718 最长重复子数组.md
          - algorithm/leetcode/1143 最长公共子序列.md
      - 模拟题:
        - algorithm/leetcode/146 LRU缓存.md
      - 数学类:
        - 丑数系列:
          - algorithm/leetcode/263 丑数.md
          - algorithm/leetcode/264 丑数II.md
        - algorithm/leetcode/204 计数质数.md
      - 待分类:
        - algorithm/leetcode/22 括号生成.md
        - algorithm/leetcode/79 单词搜索.md
        - algorithm/leetcode/84 柱状图最大的矩形.md
        - algorithm/leetcode/85 最大矩形.md
        - algorithm/leetcode/112 路径总和.md
        - algorithm/leetcode/200 岛屿数量.md
        - algorithm/leetcode/209 长度最小的子数组.md
        - algorithm/leetcode/234 回文链表.md
        - algorithm/leetcode/279 完全平方数.md
        - algorithm/leetcode/415 字符串相加（大数加法）.md
        - algorithm/leetcode/470 用rand7() 实现rand10().md
        - algorithm/leetcode/503 下一个更大元素II.md
        - algorithm/leetcode/547 省份数量.md
        - algorithm/leetcode/684 冗余连接.md
        - algorithm/leetcode/739 每日温度.md
        - algorithm/leetcode/912 排序数组.md
      - 小专题:
        - 删除有序列表的重复元素:
          - 思路: algorithm/algorithm_summary/delete_sortedlist_repeated_element.md
          - algorithm/leetcode/26 删除有序数组中的重复项.md
          - algorithm/leetcode/83 删除排序链表中的重复元素.md
          - algorithm/leetcode/82 删除排序链表中的重复元素II.md
        - 丑数系列:
          - algorithm/leetcode/263 丑数.md
          - algorithm/leetcode/264 丑数II.md
      - 刷题总结:
        - algorithm/leetcode/刷题总结.md
    - STL:
      - algorithm/STL.md
  - 配置:
    - Markdown: configuration/markdown.md
    - 服务器: configuration/server.md
    - 终端: configuration/terminal.md
    - Vscode: configuration/vscode.md
        
  - Blog:
    #TODO: think how to collect in a dir
    - blog/index.md
 